package com.tcdt.qlnvhang.request.xuathang.daugia.hopdong;

import com.tcdt.qlnvhang.entities.FileDinhKemJoinTable;
import com.tcdt.qlnvhang.request.BaseRequest;
import lombok.Data;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

@Data
public class XhHopDongHdrReq extends BaseRequest {
    private Long id;
    private Integer nam;
    private String loaiHinhNx;
    private String kieuNhapXuat;
    private Long idQdKq;
    private String soQdKq;
    private LocalDate ngayKyQdKq;
    private Long idQdPd;
    private String soQdPd;
    private String toChucCaNhan;
    private String maDviTsan;
    private LocalDate tgianXuatKho;
    private String soHopDong;
    private String tenHopDong;
    private LocalDate ngayKyHopDong;
    private LocalDate ngayHieuLuc;
    private String ghiChuNgayHluc;
    private String loaiHopDong;
    private String ghiChuLoaiHdong;
    private Integer tgianThienHdongNgay;
    private LocalDate tgianThienHdong;
    private Integer tgianBaoHanh;
    private LocalDate tgianGiaoHang;
    private Integer tgianTinhPhat;
    private BigDecimal soLuongHangCham;
    private Integer soTienTinhPhat;
    private BigDecimal giaTri;
    private LocalDate tgianBaoDamHdong;
    private String ghiChuBaoDam;
    private String dieuKien;
    private String maDvi;
    private String diaChiBenBan;
    private String mstBenBan;
    private String tenNguoiDaiDien;
    private String chucVuBenBan;
    private String sdtBenBan;
    private String faxBenBan;
    private String stkBenBan;
    private String moTaiBenBan;
    private String giayUyQuyen;
    private String tenDviBenMua;
    private String diaChiBenMua;
    private String mstBenMua;
    private String tenNguoiDdienMua;
    private String chucVuBenMua;
    private String sdtBenMua;
    private String faxBenMua;
    private String stkBenMua;
    private String moTaiBenMua;
    private String loaiVthh;
    private String cloaiVthh;
    private String tenHangHoa;
    private String moTaHangHoa;
    private BigDecimal soLuong;
    private String donViTinh;
    private BigDecimal thanhTien;
    private String ghiChu;
    private String trangThai;
    private String trangThaiXh;
    private List<String> listMaDviTsan = new ArrayList<>();
    private List<FileDinhKemJoinTable> fileCanCu = new ArrayList<>();
    private List<FileDinhKemJoinTable> fileDinhKem = new ArrayList<>();
    private List<XhHopDongDtlReq> children = new ArrayList<>();

    //Phụ lục
    private Long idHopDong;
    private String soPhuLuc;
    private LocalDate ngayHlucPhuLuc;
    private String veViecPhuLuc;
    private LocalDate ngayHlucSauDcTu;
    private LocalDate ngayHlucSauDcDen;
    private Integer soNgayThienSauDc;
    private String noiDungPhuLuc;
    private String ghiChuPhuLuc;
    private List<FileDinhKemJoinTable> filePhuLuc = new ArrayList<>();
    private List<XhHopDongHdrReq> phuLuc = new ArrayList<>();
    private List<XhHopDongDtlReq> phuLucDtl = new ArrayList<>();
    private String dvql;
}
