package com.tcdt.qlnvhang.request.xuathang.thanhlytieuhuy.thanhly;

import com.tcdt.qlnvhang.entities.FileDKemJoinTable;
import com.tcdt.qlnvhang.table.xuathang.thanhlytieuhuy.thanhly.XhTlToChucDtl;
import com.tcdt.qlnvhang.table.xuathang.thanhlytieuhuy.thanhly.XhTlToChucNlq;
import lombok.Data;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

@Data
public class XhTlToChucHdrReq {
    private Long id;
    private String maDvi;
    private Long idQdTl;
    private Long idQdTlDtl;
    private String soQdTl;
    private Integer lanDauGia;
    private String maThongBao;
    private String soQdThanhLy;
    private String trichYeuTbao;
    private String tenToChuc;
    private String sdtToChuc;
    private String diaChiToChuc;
    private String taiKhoanToChuc;
    private String nganHangToChuc;
    private String chiNhanhNhangToChuc;
    private String soHd;
    private LocalDate ngayKyHd;
    private String hthucTchuc;
    private LocalDate tgianDkyTu;
    private LocalDate tgianDkyDen;
    private String ghiChuTgianDky;
    private String diaDiemDky;
    private String dieuKienDky;
    private String tienMuaHoSo;
    private String buocGia;
    private String ghiChuBuocGia;
    private BigDecimal khoanTienDatTruoc;
    private LocalDate tgianXemTu;
    private LocalDate tgianXemDen;
    private String ghiChuTgianXem;
    private String diaDiemXem;
    private LocalDate tgianNopTienTu;
    private LocalDate tgianNopTienDen;
    private String pthucTtoan;
    private String ghiChuTgianNopTien;
    private String donViThuHuong;
    private String stkThuHuong;
    private String nganHangThuHuong;
    private String chiNhanhNganHang;
    private LocalDate tgianDauGiaTu;
    private LocalDate tgianDauGiaDen;
    private String diaDiemDauGia;
    private String hthucDgia;
    private String pthucDgia;
    private String dkienCthuc;
    private String ghiChu;
    private Integer ketQua; // 0 : Trượt 1 Trúng
    private String soBienBan;
    private String trichYeuBban;
    private LocalDate ngayKyBban;
    private String ketQuaSl;
    private Integer soDviTsan;
    private String thongBaoKhongThanh;
    private String trangThai;
    private LocalDate ngayPduyet;
    private Long nguoiPduyetId;
    private LocalDate ngayGduyet;
    private Long nguoiGduyetId;
    private Integer thoiHanThanhToan;
    private String pthucThanhtoanKhac;
    private Integer thoiHanGiaoNhan;
    private String thoiHanGiaoNhanGhiChu;
    private String pthucGnhan;
    private Long idQdPdKq;
    private String soQdPdKq;
    private Long idHopDong;
    private String soHopDong;
    private Long idQdGnv;
    private String soQdGnv;
    private List<FileDKemJoinTable> fileCanCu = new ArrayList<>();
    private List<FileDKemJoinTable> fileDinhKem = new ArrayList<>();
    private List<FileDKemJoinTable> fileDinhKemDaKy = new ArrayList<>();
    private List<XhTlToChucDtl> toChucDtl = new ArrayList<>();
    private List<XhTlToChucNlq> toChucNlq = new ArrayList<>();
}
