package com.tcdt.qlnvhang.request.xuathang.daugia.xuatkho;

import com.tcdt.qlnvhang.entities.FileDinhKemJoinTable;
import com.tcdt.qlnvhang.entities.xuathang.daugia.xuatkho.XhDgBbTinhKhoDtl;
import com.tcdt.qlnvhang.request.BaseRequest;
import lombok.Data;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

@Data
public class XhDgBbTinhKhoHdrReq extends BaseRequest {
    private Long id;
    private Integer nam;
    private String maDvi;
    private String maQhNs;
    private String soBbTinhKho;
    private LocalDate ngayLapBienBan;
    private Long idQdNv;
    private String soQdNv;
    private LocalDate ngayKyQdNv;
    private Long idHopDong;
    private String soHopDong;
    private LocalDate ngayKyHopDong;
    private String maDiemKho;
    private String diaDiemKho;
    private String maNhaKho;
    private String maNganKho;
    private String maLoKho;
    private String loaiHinhKho;
    private String loaiVthh;
    private String cloaiVthh;
    private String tenHangHoa;
    private String donViTinh;
    private String hinhThucBaoQuan;
    private LocalDate ngayBatDauXuat;
    private LocalDate ngayKetThucXuat;
    private BigDecimal tongSlNhap;
    private BigDecimal tongSlXuat;
    private BigDecimal slConLai;
    private BigDecimal slThucTe;
    private BigDecimal slThua;
    private BigDecimal slThieu;
    private String nguyenNhan;
    private String kienNghi;
    private String ghiChu;
    private Long idThuKho;
    private Long idKtvBaoQuan;
    private Long idKeToan;
    private Long idLanhDaoCuc;
    private String loaiHinhNx;
    private String kieuNhapXuat;
    private LocalDate thoiGianGiaoNhan;
    private Long idPhieuKiemNghiem;
    private String soPhieuKiemNghiem;
    private LocalDate ngayKiemNghiemMau;
    private String trangThai;
    private List<FileDinhKemJoinTable> fileDinhKem = new ArrayList<>();
    private List<XhDgBbTinhKhoDtl> children = new ArrayList<>();
    private String dvql;
    private String maDviCha;
    private LocalDate ngayLapBienBanTu;
    private LocalDate ngayLapBienBanDen;
    private LocalDate ngayBatDauXuatTu;
    private LocalDate ngayBatDauXuatDen;
    private LocalDate ngayKetThucXuatTu;
    private LocalDate ngayKetThucXuatDen;
    private LocalDate thoiGianGiaoNhanTu;
    private LocalDate thoiGianGiaoNhanDen;
}