package com.tcdt.qlnvhang.repository.quanlyphieukiemtrachatluonghangluongthuc;

import com.tcdt.qlnvhang.request.phieuktracluong.QlpktclhPhieuKtChatLuongFilterRequestDto;
import com.tcdt.qlnvhang.response.quanlyphieukiemtrachatluonghangluongthuc.QlpktclhPhieuKtChatLuongResponseDto;
import org.springframework.data.domain.Page;

public interface QlpktclhPhieuKtChatLuongRepositoryCustom {
	Page<QlpktclhPhieuKtChatLuongResponseDto> filter(QlpktclhPhieuKtChatLuongFilterRequestDto req);

	int countPhieuKiemTraChatLuong(QlpktclhPhieuKtChatLuongFilterRequestDto req);
}
